"use client"

import React, { useState } from 'react'

interface PosterFormProps {
    onGenerate: (description: string) =>  void;
}

const PosterForm = ({onGenerate}:PosterFormProps) => {

    const [description, setDescription] = useState('')

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        onGenerate(description)
    }

    return (
        <>
            <form 
                onSubmit={handleSubmit}
                className='space-y-4 bg-white p-6 rounded-xl shadow'
            >
                <h2 className='text-xl font-semibold'>
                    Create an image generated by AI
                </h2>

                <textarea 
                    placeholder='Enter your prompt'
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    rows={4}
                    className='w-full border p-2 rounded'
                    required
                />

                <span className='w-full text-sm text-gray-700'><strong>Sample Text:</strong> Create a stunning cinematic poster for a movie titled <q>[title]</q>. The plot is: <q>[description]</q>. Use vibrant colors and dramatic lighting.</span>

                <br/>

                <button
                    type='submit'
                    className='bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700'
                >
                    Generate Poster
                </button>
            </form>
        </>
    )
}

export default PosterForm